//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookWebApplication.ProductServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceReference.IRepositoryOf_Product")]
    public interface IRepositoryOf_Product {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Product/GetAllResponse")]
        ModelPoco.Product[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Product/GetAllResponse")]
        System.Threading.Tasks.Task<ModelPoco.Product[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/Find", ReplyAction="http://tempuri.org/IRepositoryOf_Product/FindResponse")]
        ModelPoco.Product Find(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/Find", ReplyAction="http://tempuri.org/IRepositoryOf_Product/FindResponse")]
        System.Threading.Tasks.Task<ModelPoco.Product> FindAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/Add", ReplyAction="http://tempuri.org/IRepositoryOf_Product/AddResponse")]
        int Add(ModelPoco.Product entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/Add", ReplyAction="http://tempuri.org/IRepositoryOf_Product/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(ModelPoco.Product entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Product/UpdateResponse")]
        void Update(ModelPoco.Product entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Product/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(ModelPoco.Product entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Product/DeleteResponse")]
        void Delete(ModelPoco.Product entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Product/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Product/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(ModelPoco.Product entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepositoryOf_ProductChannel : BookWebApplication.ProductServiceReference.IRepositoryOf_Product, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepositoryOf_ProductClient : System.ServiceModel.ClientBase<BookWebApplication.ProductServiceReference.IRepositoryOf_Product>, BookWebApplication.ProductServiceReference.IRepositoryOf_Product {
        
        public RepositoryOf_ProductClient() {
        }
        
        public RepositoryOf_ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepositoryOf_ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepositoryOf_ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepositoryOf_ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ModelPoco.Product[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ModelPoco.Product[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ModelPoco.Product Find(int ID) {
            return base.Channel.Find(ID);
        }
        
        public System.Threading.Tasks.Task<ModelPoco.Product> FindAsync(int ID) {
            return base.Channel.FindAsync(ID);
        }
        
        public int Add(ModelPoco.Product entity) {
            return base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(ModelPoco.Product entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public void Update(ModelPoco.Product entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(ModelPoco.Product entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(ModelPoco.Product entity) {
            base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(ModelPoco.Product entity) {
            return base.Channel.DeleteAsync(entity);
        }
    }
}
