//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookSaleServiceWebHost.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/ModelPoco")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ContactNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookSaleServiceWebHost.UserServiceReference.Orders[] OrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsersIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ContactNumber {
            get {
                return this.ContactNumberField;
            }
            set {
                if ((this.ContactNumberField.Equals(value) != true)) {
                    this.ContactNumberField = value;
                    this.RaisePropertyChanged("ContactNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookSaleServiceWebHost.UserServiceReference.Orders[] Order {
            get {
                return this.OrderField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderField, value) != true)) {
                    this.OrderField = value;
                    this.RaisePropertyChanged("Order");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsersID {
            get {
                return this.UsersIDField;
            }
            set {
                if ((this.UsersIDField.Equals(value) != true)) {
                    this.UsersIDField = value;
                    this.RaisePropertyChanged("UsersID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Orders", Namespace="http://schemas.datacontract.org/2004/07/ModelPoco")]
    [System.SerializableAttribute()]
    public partial class Orders : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookSaleServiceWebHost.UserServiceReference.ShoppingCart[] CartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdersIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PaymentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private BookSaleServiceWebHost.UserServiceReference.Users[] UserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookSaleServiceWebHost.UserServiceReference.ShoppingCart[] Cart {
            get {
                return this.CartField;
            }
            set {
                if ((object.ReferenceEquals(this.CartField, value) != true)) {
                    this.CartField = value;
                    this.RaisePropertyChanged("Cart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrdersID {
            get {
                return this.OrdersIDField;
            }
            set {
                if ((this.OrdersIDField.Equals(value) != true)) {
                    this.OrdersIDField = value;
                    this.RaisePropertyChanged("OrdersID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PaymentID {
            get {
                return this.PaymentIDField;
            }
            set {
                if ((this.PaymentIDField.Equals(value) != true)) {
                    this.PaymentIDField = value;
                    this.RaisePropertyChanged("PaymentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public BookSaleServiceWebHost.UserServiceReference.Users[] User {
            get {
                return this.UserField;
            }
            set {
                if ((object.ReferenceEquals(this.UserField, value) != true)) {
                    this.UserField = value;
                    this.RaisePropertyChanged("User");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCart", Namespace="http://schemas.datacontract.org/2004/07/ModelPoco")]
    [System.SerializableAttribute()]
    public partial class ShoppingCart : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShoppingCartIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShoppingCartID {
            get {
                return this.ShoppingCartIDField;
            }
            set {
                if ((this.ShoppingCartIDField.Equals(value) != true)) {
                    this.ShoppingCartIDField = value;
                    this.RaisePropertyChanged("ShoppingCartID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IRepositoryOf_Users")]
    public interface IRepositoryOf_Users {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Users/GetAllResponse")]
        BookSaleServiceWebHost.UserServiceReference.Users[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/GetAll", ReplyAction="http://tempuri.org/IRepositoryOf_Users/GetAllResponse")]
        System.Threading.Tasks.Task<BookSaleServiceWebHost.UserServiceReference.Users[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/Find", ReplyAction="http://tempuri.org/IRepositoryOf_Users/FindResponse")]
        BookSaleServiceWebHost.UserServiceReference.Users Find(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/Find", ReplyAction="http://tempuri.org/IRepositoryOf_Users/FindResponse")]
        System.Threading.Tasks.Task<BookSaleServiceWebHost.UserServiceReference.Users> FindAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/Add", ReplyAction="http://tempuri.org/IRepositoryOf_Users/AddResponse")]
        int Add(BookSaleServiceWebHost.UserServiceReference.Users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/Add", ReplyAction="http://tempuri.org/IRepositoryOf_Users/AddResponse")]
        System.Threading.Tasks.Task<int> AddAsync(BookSaleServiceWebHost.UserServiceReference.Users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Users/UpdateResponse")]
        void Update(BookSaleServiceWebHost.UserServiceReference.Users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/Update", ReplyAction="http://tempuri.org/IRepositoryOf_Users/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(BookSaleServiceWebHost.UserServiceReference.Users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Users/DeleteResponse")]
        void Delete(BookSaleServiceWebHost.UserServiceReference.Users entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRepositoryOf_Users/Delete", ReplyAction="http://tempuri.org/IRepositoryOf_Users/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(BookSaleServiceWebHost.UserServiceReference.Users entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRepositoryOf_UsersChannel : BookSaleServiceWebHost.UserServiceReference.IRepositoryOf_Users, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RepositoryOf_UsersClient : System.ServiceModel.ClientBase<BookSaleServiceWebHost.UserServiceReference.IRepositoryOf_Users>, BookSaleServiceWebHost.UserServiceReference.IRepositoryOf_Users {
        
        public RepositoryOf_UsersClient() {
        }
        
        public RepositoryOf_UsersClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RepositoryOf_UsersClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepositoryOf_UsersClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RepositoryOf_UsersClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BookSaleServiceWebHost.UserServiceReference.Users[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<BookSaleServiceWebHost.UserServiceReference.Users[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public BookSaleServiceWebHost.UserServiceReference.Users Find(int ID) {
            return base.Channel.Find(ID);
        }
        
        public System.Threading.Tasks.Task<BookSaleServiceWebHost.UserServiceReference.Users> FindAsync(int ID) {
            return base.Channel.FindAsync(ID);
        }
        
        public int Add(BookSaleServiceWebHost.UserServiceReference.Users entity) {
            return base.Channel.Add(entity);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(BookSaleServiceWebHost.UserServiceReference.Users entity) {
            return base.Channel.AddAsync(entity);
        }
        
        public void Update(BookSaleServiceWebHost.UserServiceReference.Users entity) {
            base.Channel.Update(entity);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(BookSaleServiceWebHost.UserServiceReference.Users entity) {
            return base.Channel.UpdateAsync(entity);
        }
        
        public void Delete(BookSaleServiceWebHost.UserServiceReference.Users entity) {
            base.Channel.Delete(entity);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(BookSaleServiceWebHost.UserServiceReference.Users entity) {
            return base.Channel.DeleteAsync(entity);
        }
    }
}
